!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
!                                                                             
! qpoints. Copyright (C) Antonio Cammarata 
! https://nano.cvut.cz/researchers/antonio-cammarata 
! https://orcid.org/0000-0002-5691-0682              
!                                       
! Extracts phonon eigenvectors and eigenvalues from 
! the file qpoints.yaml generated by PHONOPY 
! ( https://phonopy.github.io/phonopy )        
!                                       
! If used for production, you should cite 
! Phys. Rev. B XX, XXXXX (XXXX)    
! https://doi.org/10.1103/xxx 
!                                                                    
!    This file is part of qpoints.                                        
!                                                                      
!    qpoints is free software: you can redistribute it and/or modify 
!    it under the terms of the GNU General Public License as published by 
!    the Free Software Foundation, either version 3 of the License, or 
!    (at your option) any later version.                            
!                                                                 
!    qpoints is distributed in the hope that it will be useful, 
!    but WITHOUT ANY WARRANTY; without even the implied warranty of 
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the      
!    GNU General Public License for more details.                     
! 
!    You should have received a copy of the GNU General Public License        
!    along with phonchar.  If not, see <http://www.gnu.org/licenses/>. 
!                 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

subroutine show_logo
  use var, only: version

  write(*,'(a)')     "                     _       _        " 
  write(*,'(a)')     "    __ _ _ __   ___ (_)_ __ | |_ ___  "
  write(*,'(a)')     "   / _` | '_ \ / _ \| | '_ \| __/ __| "
  write(*,'(a)')     "  | (_| | |_) | (_) | | | | | |_\__ \ "
  write(*,'(a)')     "   \__, | .__/ \___/|_|_| |_|\__|___/ "
  write(*,'(a)')     "      |_|_|                           "
  write(*,'(*(a))')     "                              ",version
  write(*,*)
         
  
  return
end subroutine show_logo
